config/routes.rb
Rails.application.routes.draw do

  root 'robot#index'

  get 'robot/move'
  get 'robot/left'
  get 'robot/right'
  get 'robot/proximity'
  get 'robot/attack'
  get 'robot/forward'
  get 'robot/backward'
  get 'robot/slow_forward'
  get 'robot/slow_backward'
  get 'robot/run'

end

app/models/robot.rb
require 'open-uri'
class Robot

# Meta programmed version
# require 'active_support'
 # METHODS = [:lock, :forward, :backward, :slow_forward, :slow_backward, :left, :right, :run, :attack]

 # METHODS.each do |method|
 #    define_method(method) do
 #      open(@request_base+method.to_s)
 #    end
 #  end

  def initialize(user=2, port=1234)
    @request_base = "http://10.10.130.100:#{port}/#{user}/"
  end

  def hack
    user = open(@request_base+"lock").read
    replay = user.split(" ")
    unless user[0] == "OK"
      this_user = replay[-1]
      open(@request_base = "http://10.10.130.100:#{1234}/#{this_user.to_i}/")
      left
    end
  end

  def lock
    open(@request_base+"lock")
  end

  def forward
    open(@request_base+"forward")
  end

  def backward
    open(@request_base+"backward")
  end

  def slow_forward
    open(@request_base+"slow_forward")
  end

  def slow_backward
    open(@request_base+"slow_backward")
  end

  def left
    open(@request_base+"left")
  end

  def right
    open(@request_base+"right")
  end

  def run
    open(@request_base+"run")
  end

  def attack
    open(@request_base+"attack")
  end

  def proximity
    open("http://10.10.130.100:1234/proximity").read
  end

  def charge_and_exscape
    forward
    sleep(2)
    attack
    sleep(2)
    backward
  end

  def do_it
    lock
    charge_and_exscape
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/robot_controller.rb
class RobotController < ApplicationController
    #before_action :set_robot

  def index
    begin
    @proximity = @robot.proximity
    rescue Exception => e
      @proximity = 0
    end
  end

  def move
    @robot.charge_and_exscape
    redirect_to root_path
  end

  def left
    @robot.left
    redirect_to root_path
  end

  def right
    @robot.right
    redirect_to root_path
  end

  def forward
    @robot.forward
    redirect_to root_path
  end

  def backward
    @robot.backward
    redirect_to root_path
  end

  def slow_forward
    @robot.slow_forward
    redirect_to root_path
  end

  def slow_backward
    @robot.slow_backward
    redirect_to root_path
  end

  def run
    @robot.run
    redirect_to root_path
  end

  def proximity
    redirect_to root_path
  end

  def attack
    @robot.attack
    redirect_to root_path
  end

  private

  def set_robot
    @robot = Robot.new
    @robot.lock
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robot_helper.rb
module RobotHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MindStorm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


</head>
<body>

<%= yield %>

</body>
</html>

app/views/robot/index.html.erb
<div class="container">
 		<ul class="list_buttons">
			<li>
				<p><%= link_to "RELOAD PROXIMITY", root_path, class:"btn btn-info" %></p>	
			</li>
			<li>
				<p><%= link_to "MOVE ME", robot_move_path, class:"btn btn-primary" %></p>
			</li>
			<li>
				<p><%= link_to "ATTACK", robot_attack_path, class:"btn btn-danger" %></p>
			</li>
		</ul>
 
	<section class="counter">
  		<div class="ribbon"><p> <%= @proximity %> </p> 
  		</div>
  		<div class="triangle">
  		</div>
	</section>

	<div class="moves_arrows">
		<ul class="arrows_menu">
			<li><img id="backward" alt="Arrow backward" src="/assets/two_arrows_up1.png"/></li>
			<li><img id="left" alt="Arrow left" src="/assets/two_arrows_left2.png"/></li>
			<li><img id="right" alt="Arrow right" src="/assets/two_arrows_right2.png"/></li>
			<li><img id="forward" alt="Arrow forward" src="/assets/two_arrows_down1.png"/></li>
		</ul>
	</div>

</div>
<p><%= link_to "FORWARD", robot_attack_path %></p>
<p><%= link_to "LEFT", robot_left_path %></p>
<p><%= link_to "RIGHT", robot_right_path %></p>
<p><%= link_to "BACKWARD", robot_attack_path %></p>
<p><%= link_to "SLOW FORWARD", robot_attack_path %></p>
<p><%= link_to "SLOW BACKWARD", robot_attack_path %></p>
<p><%= link_to "RUN", robot_attack_path %></p>